### ISSUE TITLE
Bug on estimate parsing

### ISSUE THREAD

**Issue by kevinvaningen** [craftsmenlabs/stories#59]
The runner fails on estimations. Probably because of nulls.

Reproduction (not completely sure):
- Create stories without estimation
- Try parsing them

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
        at org.craftsmenlabs.stories.isolator.parser.converters.jira.FeatureConverter.convert(FeatureConverter.java:45)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.craftsmenlabs.stories.isolator.parser.JiraJsonParser.parse(JiraJsonParser.java:51)
        at org.craftsmenlabs.stories.importer.JiraAPIImporter.getBacklog(JiraAPIImporter.java:63)
        at org.craftsmenlabs.stories.plugin.filereader.PluginExecutor.startApplication(PluginExecutor.java:75)
        at org.craftsmenlabs.stories.plugin.filereader.BootApp.startApplication(BootApp.java:45)
        at org.craftsmenlabs.stories.plugin.filereader.BootApp.main(BootApp.java:36)
        ... 8 more

**Comment by NielsTalens** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Storynatorz](https://trello.com/c/F4wjWBXD/1-storynatorz)
